# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on: 
  schedule:
    - cron: '* * * * *'
jobs:
  test-and-upload-results:
    runs-on: ubuntu-latest
    steps:
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://github.com/swinton/screenshot-website
          destination: screenshot.png
