# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on: 
  schedule:
    - cron: '* * * * *'
jobs:
  test-and-upload-results:
    runs-on: ubuntu-latest
    steps:
      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.0.0
        with:
          token: 'd11943e967efb7764b047255befac6f0
          channels: 'general'
